# TP 1 — Introduction au calcul vectoriel


## Installation de NumPy

NumPy est une bibliothèque de calcul numérique. Elle ne fait pas partie de la bibliothèque standard de Python et doit donc être installée dans **l'environnement utilisé par Jupyter**.

Dans un terminal, après activation de l'environnement virtuel :

```bash
python -m pip install numpy
```

Avec conda :

```bash
conda install numpy
```

Depuis un notebook, la commande suivante installe NumPy dans l'environnement du noyau courant :

```python
%pip install numpy
```

Après une première installation, redémarrez le noyau si l'importation échoue encore.

Documentation : [installation de NumPy](https://numpy.org/install/).

## NumPy en quelques mots

Le principal objet fourni par NumPy est `ndarray`, un tableau de nombres à une ou plusieurs dimensions. Pour ce TP, un tableau à une dimension représentera un vecteur.

NumPy fournit notamment :

- la création de vecteurs et de matrices avec `np.array()` ;
- l'accès aux dimensions et au type des données avec `shape`, `ndim` et `dtype` ;
- les opérations coordonnées par coordonnées, sans écrire explicitement de boucle ;
- l'indexation et les tranches, comme pour les listes Python ;
- des fonctions d'agrégation comme `np.sum()` et `np.mean()` ;
- des fonctions de calcul mathématique et d'algèbre linéaire.

Références : [guide pour débuter](https://numpy.org/doc/stable/user/absolute_beginners.html), [guide de prise en main](https://numpy.org/doc/stable/user/quickstart.html), [documentation de l'API](https://numpy.org/doc/stable/reference/).

Vérifions que la bibliothèque est disponible. L'alias `np` est la convention employée dans la documentation et dans la plupart des programmes Python.

In [12]:
import numpy as np

print(np.__version__)

2.3.2


## 1. Calculer avec des listes Python

Une liste peut stocker les coordonnées d'un vecteur. Toutefois, les opérateurs des listes n'ont pas le sens des opérations vectorielles.

In [ ]:
u = [1, 2, 3]
v = [4, 5, 6]

print(u + v)
print(2 * u)

Ici, `+` concatène les listes et `*` répète leur contenu. Pour calculer avec les coordonnées, il faut parcourir les listes.

Exemple d'addition de deux vecteurs de dimension 2 :

In [ ]:
a = [2, -1]
b = [3, 4]
somme = []

for i in range(len(a)):
    somme.append(a[i] + b[i])

print(somme)

Exemple de multiplication par un scalaire :

In [ ]:
a = [2, -1]
scalaire = 3
resultat = []

for coordonnee in a:
    resultat.append(scalaire * coordonnee)

print(resultat)

### Exercice 1

1. Représentez $u = [1, 0, 3]$ et $v = [-2, 5, 1]$ avec des listes. Calculez leur addition coordonnées par coordonnées à l'aide d'une boucle. Le résultat attendu est `[-1, 5, 4]`.

In [2]:
# Vecteur u
u = [1, 0, 3]

# Vecteur v
v = [-2, 5, 1]

# List des résultats
result = []

# Addition des composants
for i in range(3):
    result.append(u[i] + v[i])

print(result)


[-1, 5, 4]


2. Calculez $2u$ puis $-3v$, toujours à l'aide de boucles.

In [9]:
# Vecteur u
u = [1, 0, 3]

# Vecteur v
v = [-2, 5, 1]

# --- Calcul de 2u ---
print("### Calcul de 2u ###")
liste_2u = []
for i in range(len(u)):
    element = u[i] * 2
    liste_2u.append(element)

print(f"  Résultat : {liste_2u}")

# --- Calcul de -3v ---
print("\n### Calcul de -3v ###")
liste_minus_3v = []
for i in range(len(v)):
    element = v[i] * -3
    liste_minus_3v.append(element)

print(f"  Résultat : {liste_minus_3v}")


### Calcul de 2u ###
  Résultat : [2, 0, 6]

### Calcul de -3v ###
  Résultat : [6, -15, -3]


3. Calculez la combinaison linéaire $2u - 3v$.

In [10]:
print("\n### Calcul de 2u-3v ###")

liste_2u_3v = []

for i in range(len(u)):
    liste_2u_3v.append(2 * u[i] - 3 * v[i])

print(f"  Résultat : {liste_2u_3v}")


### Calcul de 2u-3v ###
  Résultat : [8, -15, 3]


Le produit scalaire s'obtient en multipliant les coordonnées correspondantes, puis en additionnant les produits.

In [7]:
a = [2, -1, 3]
b = [1, 4, 2]
produit = 0

for i in range(len(a)):
    produit = produit + a[i] * b[i]

print(produit)

4


4. Écrivez une fonction `produit_scalaire(u, v)` qui reprend ce calcul et renvoie un nombre. Testez-la sur les vecteurs de l'exemple, puis sur ceux de la première question.

In [8]:
def produit_scalaire(u, v):
    produit = 0
    for i in range(len(v)):
        produit += u[i] * v[i]
    return produit

produit_scalaire(a, b)
produit_scalaire(u, v)

1

## 2. Calculer avec NumPy

`np.array()` transforme une liste en tableau NumPy. Les tableaux numériques contiennent normalement des valeurs d'un même type.

In [13]:
u_np = np.array([1, 0, 3])
v_np = np.array([-2, 5, 1])

print(u_np)
print(type(u_np))
print(u_np.ndim)
print(u_np.shape)
print(u_np.dtype)

[1 0 3]
<class 'numpy.ndarray'>
1
(3,)
int64


Pour deux tableaux de même dimension, les opérations arithmétiques sont appliquées coordonnées par coordonnées.

In [14]:
print(u_np + v_np)
print(2 * u_np)
print(u_np * v_np)
print(np.sum(u_np))
print(np.mean(u_np))

[-1  5  4]
[2 0 6]
[-2  0  3]
4
1.3333333333333333


Le produit `u_np * v_np` est une multiplication coordonnée par coordonnée. Le produit scalaire est calculé avec `np.dot(u_np, v_np)` ou `u_np @ v_np`.

Documentation : [`np.array`](https://numpy.org/doc/stable/reference/generated/numpy.array.html), [`np.dot`](https://numpy.org/doc/stable/reference/generated/numpy.dot.html).

In [15]:
print(np.dot(u_np, v_np))
print(u_np @ v_np)

1
1


### Exercice 2

1. Reprenez les vecteurs $u$ et $v$ de l'exercice précédent sous forme de tableaux NumPy. Calculez directement $u+v$, $2u$, $-3v$ et $2u-3v$.

In [23]:
u = np.array([1, 0, 3])
v = np.array([-2, 5, 1])

print(f"u + v: {u+v}")
print(f"2u: {2*u}")
print(f"-3v: {-3*v}")
print(f"2u - 3v: {2*u - 3*v}")

u + v: [-1  5  4]
2u: [2 0 6]
-3v: [  6 -15  -3]
2u - 3v: [  8 -15   3]


2. Calculez leur produit coordonnée par coordonnée, puis leur produit scalaire. Vérifiez le produit scalaire avec les deux syntaxes présentées.

In [26]:
print(f"Produit coordonnée par coordonnée: {u * v}")
print(f"Produit scalaire: {u @ v}")
print(f"Produit scalaire: {np.dot(u, v)}")

Produit coordonnée par coordonnée: [-2  0  3]
Produit scalaire: 1
Produit scalaire: 1


3. Créez le vecteur `[0.5, 1.5, -2.0, 4.0]`. Affichez sa dimension, sa forme et son type de données, puis calculez la somme et la moyenne de ses coordonnées.

In [33]:
vecteur = np.array([0.5, 1.5, -2.0, 4.0])
print(f"Forme: {vecteur.shape}")
print(f"Dimension: {len(vecteur)}")
print(f"Type de données: {vecteur.dtype}")

print(f"Somme: {sum(vecteur)}")
print(f"Somme: {vecteur.mean()}")

Forme: (4,)
Dimension: 4
Type de données: float64
Somme: 4.0
Somme: 1.0


## 3. Implémenter la norme euclidienne

Pour $u = [u_1, …, u_n]$ :

$$\lVert u \rVert = \sqrt{u_1^2 + … + u_n^2} = \sqrt{u \cdot u}.$$

La fonction `sqrt()` du module standard `math` calcule une racine carrée.

In [36]:
from math import sqrt

print(sqrt(25))

5.0


### Exercice 3

1. Écrivez une fonction `norme(u)` qui reçoit un vecteur représenté par une liste Python et renvoie sa norme. Utilisez une boucle ou la fonction `produit_scalaire()` écrite plus haut.

In [37]:
def norme(u):
    return sqrt(produit_scalaire(u, u))

2. Vérifiez la fonction sur `[3, 4]`, `[1, 0, 0]`, `[0, 0, 0]` et `[2, -1, 2]`. Les résultats attendus sont respectivement 5, 1, 0 et 3.

In [38]:
print(norme([3, 4]))
print(norme([1, 0, 0]))
print(norme([0, 0, 0]))
print(norme([2, -1, 2]))

5.0
1.0
0.0
3.0


3. Écrivez `norme_numpy(u)` pour un tableau NumPy. Utilisez `np.dot()` et `np.sqrt()`, sans boucle.

In [ ]:
def norme_numpy(u):
    return np.sqrt(np.dot(u, u))

4. NumPy fournit déjà `np.linalg.norm()`. Comparez les résultats de votre fonction avec ceux de NumPy sur les quatre vecteurs précédents.

Documentation : [`np.linalg.norm`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html).

In [43]:
print(norme_numpy([3, 4]))
print(f"Built-in: {np.linalg.norm([3, 4])}")

print(norme_numpy([1, 0, 0]))
print(f"Built-in: {np.linalg.norm([1, 0, 0])}")

print(norme_numpy([0, 0, 0]))
print(f"Built-in: {np.linalg.norm([0, 0, 0])}")

print(norme_numpy([2, -1, 2]))
print(f"Built-in: {np.linalg.norm([2, -1, 2])}")


5.0
Built-in: 5.0
1.0
Built-in: 1.0
0.0
Built-in: 0.0
3.0
Built-in: 3.0


## 4. Implémenter la similarité cosinus

Pour deux vecteurs non nuls :

$$\cos(u,v) = \frac{u \cdot v}{\lVert u \rVert\,\lVert v \rVert}.$$

La fonction devra renvoyer `None` si l'un des deux vecteurs est nul, car le dénominateur vaudrait alors zéro.

### Exercice 4

1. Écrivez une fonction `cosinus(u, v)` pour des listes Python. Réutilisez `produit_scalaire()` et `norme()` au lieu de recopier leurs calculs.

In [49]:
def cosinus(u, v):
    try:
        return produit_scalaire(u, v)/(norme(u)*norme(v))
    except ZeroDivisionError:
        print("La similarité cosinus est non-définie.")

2. Testez la fonction sur les paires suivantes et interprétez les résultats :

- `[1, 0]` et `[4, 0]` ;
- `[1, 0]` et `[0, 3]` ;
- `[1, 2]` et `[-1, -2]` ;
- `[1, 2]` et `[0, 0]`.

In [50]:
print(cosinus([1, 0], [4, 0]))

print(cosinus([1, 0], [0, 3]))

print(cosinus([1, 2], [-1, -2]))

print(cosinus([1, 2], [0, 0]))

1.0
0.0
-0.9999999999999998
La similarité cosinus est non-définie.
None


3. Écrivez `cosinus_numpy(u, v)` pour des tableaux NumPy. Réutilisez `norme_numpy()` et `np.dot()`.

In [52]:
def cosinus_numpy(u, v):
    return np.dot(u, v)/(norme_numpy(u)*norme_numpy(v))

4. Les vecteurs suivants représentent trois mots dans un espace fictif. Calculez la similarité de `chat` avec `chien` puis avec `voiture`. Quel mot est le plus proche de `chat` selon cette mesure ?

In [55]:
chat = np.array([0.8, 0.7, 0.1])
chien = np.array([0.75, 0.65, 0.2])
voiture = np.array([0.1, 0.2, 0.9])

In [57]:
print(f"Chat - chien {cosinus_numpy(chat, chien)}")
print(f"Chat - voiture {cosinus_numpy(chat, voiture)}")

# Chien est plus proche que voiture de chat

Chat - chien 0.9944755403439138
Chat - voiture 0.313083400758126


In [ ]:
10*chat

SyntaxError: invalid decimal literal (4027939607.py, line 1)

5. Facultatif : multipliez le vecteur `chat` par 10 et recalculez les deux similarités. Expliquez en une phrase pourquoi elles ne changent pas.

In [63]:
print(f"Cosinus 10xchat - chien {cosinus_numpy(10*chat, chien)}")
print(f"Cosinus chat - chien {cosinus_numpy(chat, chien)}")

# La similarité cosinus mesure l'angle entre les vecteurs et non pas leur longueur.

Cosinus 10xchat - chien 0.9944755403439136
Cosinus chat - chien 0.9944755403439138


## Pour aller plus loin

- [Indexation des tableaux NumPy](https://numpy.org/doc/stable/user/basics.indexing.html)
- [Fonctions mathématiques](https://numpy.org/doc/stable/reference/routines.math.html)
- [Algèbre linéaire avec NumPy](https://numpy.org/doc/stable/reference/routines.linalg.html)