# Rappels de Python - Partie 1 - Variables, types et stockage des données

Il s'agit d'une introduction très rapide à Python, suffisante pour passer au reste du cours.

Pour aller plus loin, je vous recommande vivement de suivre le [tutoriel Python](https://docs.python.org/3/tutorial).

**Prérequis** :
- Une installation fonctionnelle de Python >= 3.8
- Une installation fonctionnelle de la version correspondante de pip

> Notez que tout au long de ce tutoriel, vous devrez utiliser l'exécutable Python correct sur votre système

## Création d'un environnement virtuel et exécution de Jupyter Notebook

Tous les travaux pratiques de ce cours seront réalisés à l'aide de Python et de [Jupyter](https://jupyter.org/), un environnement de développement interactif basé sur le Web.


Pour installer Jupyter notebook, suivez les étapes suivantes dans votre terminal :

0. Accédez au dossier dans lequel vous avez téléchargé le dossier prog_basics.


1. Créez un environnement virtuel (une arborescence de répertoires autonome qui contient une installation Python pour une version particulière de Python, ainsi qu'un certain nombre de paquets supplémentaires).

>```python -m venv venv```

2. Activez l'environnement virtuel
>```source venv/bin/activate```
ou
>```./venv/Scripts/activate```

3. Installez Jupyter
> ```pip install jupyter```

4. Lancez le notebook Jupyter pour aujourd'hui
> ```jupyter notebook lab0_introduction.ipynb```

### Exercice : installer votre propre paquet
Installez le paquet **numpy** (`pip install numpy`) dans votre environnement et vérifiez que l'importation fonctionne en exécutant :

## Variables

Une **variable** est un nom symbolique qui permet de stocker et de manipuler des données dans la mémoire de l’ordinateur. 

Une variable peut contenir différents types de valeurs, et contrairement à certains autres langages, Python **n’exige pas de déclaration de type préalable** : le type est déterminé automatiquement lors de l’affectation. Le contenu d'une variable peut être écrasé par une valeur d'un autre type que le type utilisé lors de la déclaration de la variable.

**Notions de base sur les variables**:
- Types de base : 
    - `int` (entiers, possiblement négatif) 
    - `float` (ensemble des nombres réels)
    - `str` (chaînes de caractère) 
    - `bool` (booléen, 
    vaut 0/False ou 1/True)
- L'affectation d'une valeur dans une variable se fait avec `=`
- On peut obtenir le type d'une variable grâce à la fonction `type`.
- Les conversions de type se font avec `int()`, `float()`, `str()`
- La fonction `print` permet d'afficher le résultat à l'utilisateur
- Les lignes commençant par `#` sont des commentaires qui sont ignorés par l'interpréteur.

### Exercices
1. Créez une variable `x` égale à 10. Faîtes un `print` de son type.
2. Créez une variable `y` égale à 3.5. Faîtes un `print` de son type.
3. Convertissez `y` en entier et affiche le résultat.
4. Créez une variable `nom` contenant votre prénom et affichez-la.

## Principaux opérateurs

Python propose les principaux opérateurs pour la manipulation de nombre et la création d'expression logique.

- Opérateurs arithmétiques : `+`, `-`, `*`, `/`, `//`, `%`, `**`
- Opérateurs logiques : `and`, `or`, `not`
- Opérateurs de comparaison : `==`, `!=`, `<`, `>`, `<=`, `>=`
- Modulo : `%`

### Exercices
1. Calcule et affiche "7 plus (3 multiplié par 2)".
2. Calcule la division entière et le reste de 17 par 5.
3. Vérifie si `10` est supérieur à `5` et inférieur à `20`.
4. Vérifie si `x` est pair en utilisant le modulo (`%`).

## Stockage de données

⚠️ Bien maîtriser les différentes possibilités pour stocker des données en Python, c'est la **base** pour se sentir à l'aise en Python et toujours faire les choix adéquats pour la résolution de problème.
Vu l'importance de la question, nous allons y consacrer une séance entière CM et TP sur cette question, ce TP est présenté comme une introduction. À chaque exemple, essayer de deviner ce que fait le code et exécutez le.

### Les listes
Une liste est une collection ordonnée (c'est à dire que l'ordre des éléments ne va pas changer) et mutable (c'est à dire que les éléments peuvent être modifiés). Elle peut contenir en Python des éléments de types différents. Elles ont la particularité en Python d'être indexées à partir de 0. Un certain nombre de méthodes sur ces listes sont disponibles, afin **d'accéder aux différents éléments** et de **modifier les contenus des listes**.

In [2]:
ma_liste = [1, "bonjour", 3.14, True]

print("Pouvez-vous donner les différents types des objets dans la liste ?", ma_liste)

Pouvez-vous donner les différents types des objets dans la liste ? [1, 'bonjour', 3.14, True]


Récupérer un élément est fait en utilisant la notation [] en précisant l'index de l'élément souhaité. Les indexs négatifs prennent les indices à l'envers.

In [3]:
print("Premier élément :", ma_liste[0])
print("Dernier élément :", ma_liste[-1])

Premier élément : 1
Dernier élément : True


Il est aussi possible de récupérer tout un pan de liste en utilisant la notation `:` (attention, le dernier élément n'est pas pris en compte dans l'indice). Par exemple, `1:4` retourne les éléments entre l'indice 1 (donc le deuxième élément) et l'indice 3. L'indice vide à gauche indique le premier élément et à droite indique le dernier élément.

In [ ]:
print(ma_liste[:3]) # Print the first 2 elements
print(ma_liste[2:3]) # Print only the third element
print(ma_liste[1:3]) # Print the second and the third element

La méthode `append` permet d'ajouter un élément à la liste, à chaque fois à la fin d'une liste. La méthode `pop` permet d'enlever un élément à index donné (par défaut, enlève le dernier élément seulement).

In [4]:
ma_liste.append(4)
print(ma_liste)

ma_liste.pop() # Enlève le dernier élément
print(ma_liste)

ma_liste.pop(0) # Enlève le premier élément.
print(ma_liste) 


[1, 'bonjour', 3.14, True, 4]
[1, 'bonjour', 3.14, True]
['bonjour', 3.14, True]


**Exercices sur les listes**:
1. Créez une liste qui contient les chiffres de 1 à 10.
2. Rajoutez l'élément 4 à la fin.
3. Imprimez les 2 premiers éléments.
4. Supprimez le 3ème élément.
5. Rajoutez l'élément 5 en 4ème position.

### Les sets
Un set est une collection NON ordonnée et sans doublon. **On s'en sert donc lorsque l'on souhaite stocker des données sans répétition, ou bien forcer l'unicité des éléments d'une liste**.
On peut faire des opérations ensemblistes : union (|) et intersection (&). On peut aussi ajouter un élément à l'aide de la méthode `add` and `discard`.


In [ ]:
mon_set = {1, 2, 3, 3}
print("Set (pas de doublons) :", mon_set)

mon_set.add(4)
mon_set.discard(2)
print("Après modifications :", mon_set)

autre_set = {3, 4, 5}
print("Union :", mon_set | autre_set)
print("Intersection :", mon_set & autre_set)

**Exercices**:
1. Créez le set `mon_set` (1, 2, 2, 3) et constatez qu'il n'y a pas de doublon.
2. Supprimez les doublons de la liste [1, 1, 2, 2, 3] et stockez le sous la variable `sans_doublon`.
3. Ajoutez le nombre `5` à l’ensemble.
4. Supprimez le nombre `2` de l’ensemble.
5. Trouvez l'intersection entre (1, 2, 2, 3) et [1, 1, 2, 2, 3].

### Les dictionnaires
Un dictionnaire associe des **clés à des valeurs** (mapping). Les clés sont uniques et doivent être immuables (ex: str, int, tuple).
On peut récupérer la valeur associée à une clé à l'aide des []. Les méthodes `values` et `keys` permettent d'obtenir l'ensemble des valeurs et des clés dans le dictionnaire.

In [1]:
mon_dict = {"Alice": 15, "Bob": 12, "Chloé": 18}
print("Dictionnaire :", mon_dict)
print("Note de Bob :", mon_dict["Bob"])

# Ajout / modification
mon_dict["David"] = 14
print("Après ajout :", mon_dict)

# Suppression
del mon_dict["Alice"]
print("Après suppression :", mon_dict)

# Obtention de l'ensemble des clés
print(mon_dict.keys())

# Obtention de l'ensemble des valeurs
print(mon_dict.values())

Dictionnaire : {'Alice': 15, 'Bob': 12, 'Chloé': 18}
Note de Bob : 12
Après ajout : {'Alice': 15, 'Bob': 12, 'Chloé': 18, 'David': 14}
Après suppression : {'Bob': 12, 'Chloé': 18, 'David': 14}
dict_keys(['Bob', 'Chloé', 'David'])
dict_values([12, 18, 14])


**Exercices**:
1. Démontrez qu'une liste ne peut pas être une clé valide d'un dictionnaire.
2. Créez un dictionnaire qui associe à 3 pays une capitale.
4. Imprimez les trois pays.
5. Imprimez les trois capitales.
6. Associez "Melbourne" à l'Australie.
7. Éditez la valeur pour l'Australie en Canberra.
8. Supprimez la valeur pour l'Australie.

# Rappels de Python - Partie 2 - Structures de contrôles et gestion des erreurs

L'une des caractéristiques principales de Python est que l'indentation conditionne l'exécution du code, et **ne relève pas uniquement de l'esthétique**.
Contrairement à d’autres langages qui utilisent des accolades {} ou des mots-clés pour délimiter les blocs, Python se base uniquement sur l’indentation (espaces ou tabulations) pour déterminer quels instructions appartiennent à quel bloc.

Un bloc de code, caractérisé par une indentation d'une `tab` ou de `4 espaces`, représente une séquence d'instruction qui doivent être exécutées ensemble.

- les structures conditionnelles (`if, elif, else`)
- les boucles (`for, while`)
- les définitions de fonctions (`def`) et de classes (`class`)

Toute erreur d’alignement (trop d’espaces, pas assez, mélange d’espaces et de tabulations) génère une `IndentationError`, et le programme ne s’exécute pas.


### Les structures `if` / `elif` / `else`

Les structures conditionnelles permettent d’exécuter un bloc de code uniquement si une **condition est vraie**. 
Cette condition permet de filtrer si jamais l'interpréteur doit "rentrer dans la condition", et exécuter le code qui y est indenté.

```python
if condition:
    # bloc exécuté si condition True
elif autre_condition:
    # bloc exécuté si autre_condition True
else:
    # bloc exécuté si aucune condition n'est vraie
```

**Exercices**:

1. Générez une erreur `IndentationError` en réalisant la mauvaise indentation de votre code dans une condition `if`/`else`.
2. Réalisez un bloc de condition qui `print` "Enfant" si la variable `age` est inférieure à 12, "Adolescent" si l'âge est entre 12 et 18, et Adulte sinon.
3. Réalisez un bloc de condition qui `print` "Pair" si la variable `x` est divisible par 2, sinon "Impair".

In [2]:
# Votre code ici

### Les structures de boucle

#### La structure `for`
La boucle for permet d’itérer sur une séquence (liste, chaîne, range, etc.), appelé en Python `Iterable`, et d’exécuter un bloc de code pour chaque élément de l'itération.

```python
for i in range(5):
    print(i)  # affiche 0, 1, 2, 3, 4
```

##### Exercices
1. Affichez tous les nombres pairs entre 1 et 20 à l'aide d'une boucle `for`.
2. Calculez la somme des éléments entre 0 et 100 (sans utiliser `sum` ou la formule de Gauss).
3. Calculez la somme des carrés des nombres de 1 à 20.
4. Étant donné une liste de nombres `[3, 8, 12, 5, 7, 20]`, créez une nouvelle liste contenant seulement les nombres supérieurs à 10.

In [ ]:
# Votre code ici

#### La structure `while`

La boucle while répète un bloc tant qu’une condition est vraie.

⚠️ **Une boucle `while` peut être infinie, il faut bien s'assurer que la conidition de sortie soit réalisable.**

```
i = 0
while i < 5:
    print(i)
    i += 1
```

Deux instructions permettent d'affecter le comportement de la boucle `while`:
- `break` : quitte immédiatement la boucle.
- `continue` : passe à l’itération suivante, en sautant le reste du bloc. 

##### Exercices
1. À l'aide d'une boucle `while`, faire un `print` de tous les éléments entre 1 et 10.
2. Avec une boucle `while` et le mot clé `continue`, affichez les nombres de 1 à 20, mais sautez tous les multiples de 3.
3. La fonction `input` permet de demander une entrée à l'utilisateur, qui sera stocké dans une variable. Le retour de l'utilisateur est stocké dans la variable qui est mise dans le retour de `input` (par exemple, `input = input("Donne moi un chiffre")` stockera dans `input` la valeur donnée par l'utilisateur).
Réalisez un bloc de code demandant itérativement une valeur à l'utilisateur à l'aide d'une boucle `while`, et sortez de la boucle lorsque la somme des valeurs entrées dépasse 100.
4. Demandez des nombres à l’utilisateur jusqu’à ce qu’il saisisse 0, puis à l'aide de `continue`, affichez uniquement les nombres pairs.

## La gestion des erreurs

En Python, il est fréquent que certaines instructions puissent provoquer des erreurs (ou exceptions) lors de l’exécution du programme. Ces erreurs peuvent provenir, par exemple :
- de la division par zéro (`ZeroDivisionError`)
- de l’accès à un indice inexistant dans une liste (`IndexError`)
- de la conversion d’une chaîne en entier qui n’est pas un nombre (`ValueError`)

Pour éviter que le programme s’arrête brutalement, Python propose des mécanismes pour capturer et gérer ces erreurs.

La syntaxe standard consiste à utiliser un bloc `try/except`:

```
try:
    # bloc de code à surveiller

    x = int(input("Saisis un nombre : "))
    resultat = 10 / x

except ZeroDivisionError:
    print("Erreur : division par zéro !")
    
except ValueError:
    print("Erreur : saisie invalide, ce n'est pas un nombre !")
```

Dans le cas où le type d'erreur n'est pas clair, on peut utiliser l'expression fourre-tout `Exception`.


#### Exercices
1. Créez une liste de 5 éléments et demande à l’utilisateur un indice afin d'afficher le chiffre correspondant dans la liste, en ajoutant une gestion d'erreur dans le cas où l'indice ne correspond pas à un élément dans la liste.
2. Demandez un nombre à l’utilisateur et le convertir en entier. Si la saisie est incorrecte, affiche un message d’erreur et redemandez à l'utilisateur en lui laissant 3 tentatives. Sinon affichez "Nombre de tentatives dépassées".

# Partie 3 : Fonctions et première résolution de problèmes

## La fonction range
La fonction `range()` est très utilisée en Python pour générer des séquences de nombres.
Elle est particulièrement utile dans les boucles `for`.

Elle peut s'utiliser de trois manières :

- `range(stop)` – génère les nombres de 0 à `stop-1`
- `range(start, stop)` – génère les nombres de `start` à `stop-1` 
(⚠️ comme pour le slicing, le stop retourne à l'indice stop-1)
- `range(start, stop, step)` – génère les nombres de `start` à `stop-1` en ajoutant `step` à chaque itération

In [ ]:
print(list(range(5))) # Tous les nombres entre 0 et 4
print(list(range(2, 5))) # Tous les nombres entre 2 et 4
print(list(range(1, 4, 2))) # Tous les nombres entre 1 et 4 par pas de 2

[0, 1, 2, 3, 4]
[2, 3, 4]
[1, 3]


## Compréhension de liste (list comprehension)

Une **compréhension de liste** est une façon concise de créer une liste à partir d'un itérable.

Sa syntaxe générale est :
     `[expression for élément in itérable]`
itérable peut être un dictionnaire, une liste, un set ...

Cela permet d'écrire du code plus court et plus lisible plutôt que de devoir passer systématiquement par une boucle `for`.

In [3]:
# Exemple 1 : Création d'une liste des carrés de 0 à 9
cubes = [x**3 for x in range(10)]
print(cubes)

# Équivalent sans compréhension de liste :
cubes_equiv = []
for x in range(10):
    cubes_equiv.append(x**3)
print(cubes_equiv)

# ---------------------------------------------------
# Exemple 2 : Transformer tous les mots en majuscules
mots = ["chat", "chien", "lapin"]
majuscules = [mot.upper() for mot in mots]
# ⚠️ Les objets de type str possèdent de nombreuses méthodes pour les transformer, nous en verrons au fur et à mesure des TP.
print(majuscules)

# ---------------------------------------------------
# Exemple 3 : Filtrer avec une condition
pairs = [x for x in range(20) if x % 2 == 0]
print(pairs)

# ---------------------------------------------------
#  Exemple 4 : Liste de listes (imbriquées)
table_de_3 = [[i, i*3] for i in range(1, 6)]
print(table_de_3)

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]
[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]
['CHAT', 'CHIEN', 'LAPIN']
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[[1, 3], [2, 6], [3, 9], [4, 12], [5, 15]]


**Exercices**:
1. Ré-écrivez la boucle suivante en compréhension de liste.
```
liste = [2, 3, 4]
for ix in liste:
    print(ix)
```
2. Filtrer tous les nombres divisibles par trois entre 1 et 40.

## La fonction `enumerate`
La fonction `enumerate()` permet de parcourir une liste en obtenant à la fois:
 - L'indice de l'élément courant
 - La valeur de l'élément
Il est possible de décaler la valeur des indices retournés grâce à l'argument `start`.


In [11]:
fruits = ["pomme", "banane", "cerise"]

for index, fruit in enumerate(fruits):
    print(f"Numéro {index} : {fruit}")

for index, fruit in enumerate(fruits, start=2):
    print(f"Numéro {index} : {fruit}")

Numéro 0 : pomme
Numéro 1 : banane
Numéro 2 : cerise
Numéro 2 : pomme
Numéro 3 : banane
Numéro 4 : cerise


## Définir une fonction
Les **fonctions** sont un élément fondamental en programmation. Elles permettent de définir des blocs réutilisables, qui vont prendre en entrée des variables (les *arguments* ou bien *paramètres*) et qui vont retourner une sortie.

**Elles permettent de regrouper du code afin qu'il puisse être réutilisé facilement.**

En Python, on utilise le mot clé `def` pour définir une fonction et le mot clé `return` pour retourner la sortie :

```python
def nom_de_fonction(param1, param2, ...):
     """Chaîne de documentation (optionnelle)"""
     # bloc de code
     return resultat  # (optionnel)
```

On appelle ensuite la fonction en utilisation la syntaxe `nom_de_fonction()`.

Il est possible de passer des arguments par défaut en les spécifiant lors de la définition des arguments.

```python
def nom_de_fonction(param1, param_defaut = "defaut"):
     """Chaîne de documentation (optionnelle)"""
     # bloc de code
     return resultat  # (optionnel)
```

In [19]:
# Fonction sans paramètre
def aime_le_cours():
    """Affiche un message de bienvenue."""
    print("J'aime le cours d'algorithmique pour les SHS!")

# Appel de la fonction
aime_le_cours()

# Fonction avec un paramètre
def aime_le_cours(nom_du_cours):
    """Affiche un message personnalisé."""
    print(f"J'aime {nom_du_cours} !")
    # Il s'agit d'une manière de formatter les strings, qui utilise la syntaxe f, avec des
    # accolades.

# Appel de la fonction en spécifiant un paramètre
aime_le_cours("Algorithmique pour les SHS")

# Fonction avec un paramètre par défaut
def aime_le_cours(nom_du_cours="Algorithmique pour les SHS"):
    """Affiche un message personnalisé."""
    print(f"J'aime {nom_du_cours} !")

# Sans spécifier de paramètres
aime_le_cours()
# En spécifiant un paramètre
aime_le_cours("TALxIA")

# Fonction avec un retour
def carre(x):
    """Retourne le carré de x."""
    return x * x

resultat = carre(5)
print("Le carré de 5 est :", resultat)



J'aime le cours d'algorithmique pour les SHS!
J'aime Algorithmique pour les SHS !
J'aime Algorithmique pour les SHS !
J'aime TALxIA !
Le carré de 5 est : 25


**Exercices:**
1. Écrivez une fonction `cube(n)` qui retourne le cube de n et testez la pour différentes valeurs de *n*.
2. Écrivez une fonction `puissance(base, exposant)` qui calcule la base à la puissance exposant.
3. Écrivez une fonction `convertir_temperature(temp, unite="C")` qui :
    - si unite == "C", retourne la température en Fahrenheit
    - si unite == "F", retourne la température en Celsius

Avec les formules de conversion suivantes :

    °F = °C × 9/5 + 32

    °C = (°F − 32) × 5/9

## Manipulation de fichiers

Python offre des moyens simples pour lire et écrire des fichiers, ce qui est essentiel pour lire et pour écrire des données.

In [1]:
with open("data/sample.txt", "r", encoding="utf-8") as f:
    content = f.read()
    print(content)

ceci est un test!
il s'agit du TP de révision


avec les arguments : 
- « r » = mode lecture (autres modes : « w » pour écriture, « a » pour ajout)
- encoding=« utf-8 », en fonction de la langue analysée.
- Utilisation du mot-clé with pour créer un **contexte** qui ferme automatiquement le fichier après utilisation.

ou ouvert et lu ligne par ligne :

In [2]:
with open("data/sample.txt", "r", encoding="utf-8") as f:
    for ix, line in enumerate(f):
        line = line.strip()
        print(f"LINE {ix}:", line)

LINE 0: ceci est un test!
LINE 1: il s'agit du TP de révision


Files can be overwritten using the "w" keyword to **overwrite** and the "a" keyword to **append**.

In [ ]:
lines = ["This is line 1", "This is line 2"]

with open("output.txt", "w", encoding="utf-8") as f:
    for l in lines:
        f.write(l + "\n")

**Exercices :**

1. Lisez le fichier `pos_analysis.txt` et renvoyez sous forme de liste les mots dont la catégorie grammaticale est NOUN.
2. Le fichier `french_UD_sample.conllu` contient un petit échantillon de dépendance universelle (à voir dans les prochaines leçons !)
    - Chargez le fichier dans Python et essayez de comprendre sa structure.
    - Renvoyez le nombre de phrases balisées dans le fichier.
    - Construisez une liste « auxiliary » contenant tous les mots étiquetés comme AUX et une liste « adjective » contenant tous les adjectifs.
3. **Pour aller plus loin**: écrivez le contenu de tous les mots contenus dans `auxiliary` dans le fichier `auxiliary.txt`.

## Manipulation de tableaux et numpy

Pour cette section, vous devrez installer la bibliothèque `numpy` dans votre environnement (`pip install numpy`).
La lecture de la documentation sera très utile pour le laboratoire de cette année : `https://numpy.org`.

Elle permet de créer des objets itérables plus rapidement et de manière plus efficace en termes de mémoire que les listes Python pour les opérations numériques.

In [5]:
import numpy as np

# Create from a Python list
a = np.array([1, 2, 3, 4])
print("Array a:", a)

# Create a 2D array (matrix)
b = np.array([[1, 2], [3, 4]])
print("Array b:\n", b)

Array a: [1 2 3 4]
Array b:
 [[1 2]
 [3 4]]


`numpy` est particulièrement utile pour les multiplications *pair-wise*.

In [6]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

print(x + y)
print(x * y) 
print(x ** 2)

[11 22 33]
[10 40 90]
[1 4 9]


Et pour l'accès à un certains nombres de fonctions statistiques.

In [7]:
arr = np.array([1, 2, 3, 4, 5])
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Square roots:", np.sqrt(arr))

# On table row
d = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
d.mean(axis=1)

Sum: 15
Mean: 3.0
Max: 5
Square roots: [1.         1.41421356 1.73205081 2.         2.23606798]


array([2., 5., 8.])

**Exercices :** 

1. Élevez chaque élément de [2, 3, 4] au cube sans utiliser de boucle « for ».
2. Renvoyez chaque élément supérieur à la moyenne.
3. Renvoyez la somme par ligne de chaque élément.
4. Créez un tableau aléatoire à l'aide de « np.random.randint ».
5. Comptez le nombre d'éléments pairs.

## Pour aller plus loin : résolutions de problème
Cette partie contient des problèmes de réflexion plus compliqués à résoudre en Python en utilisant les concepts vus tout au long des séances. **Ceux-ci doivent être finis à la maison**.

##### Problème 1 : Somme des indices pairs

Écrivez une fonction `somme_indices_pairs(liste)` qui :
- prend une liste de nombres en entrée,
- calcule et retourne la somme des éléments situés à un index pair (0, 2, 4, …).

```python
somme_indices_pairs([10, 20, 30, 40, 50])  # Retourne 10 + 30 + 50 = 90
```

##### Problème 2 : Trouver les doublons d'une liste
Écrivez une fonction `trouver_doublons(liste)` qui :
- prend une liste de nombres ou de chaînes,
- retourne une liste contenant tous les éléments qui apparaissent plus d’une fois, sans répétition dans le résultat.

```python
trouver_doublons([1, 2, 3, 2, 4, 1, 5])  # Retourne [1, 2]
```

##### Problème 3 : Mot le plus long
Écrivez une fonction `mot_plus_long(phrases)` qui :
- prend une liste de phrases (chaînes de caractères),
- retourne le mot le plus long parmi toutes les phrases et la phrase dans laquelle il apparaît.


👉 **Indice** : on peut couper une chaîne de caractère sur les espaces grâce à la méthode `split()`
```python
"ceci est un".split() = ["ceci", "est", "un"]
```

```python
phrases = ["Bonjour à tous", "Python est fantastique", "J'aime coder"]
mot_plus_long(phrases)
# Retourne ("fantastique", "Python est fantastique")
```

##### Problème 4
Écrivez une fonction `frequence_lettres(texte)` qui : 
- prend en entrée une chaîne de caractères texte,
- ignore la casse (majuscule/minuscule) (👉 **Indice** : la méthode `lower` permet de récupérer une chaîne de caractère en minuscule : `"Test".lower() = "test"`)
- compte combien de fois chaque lettre de l’alphabet apparaît dans le texte
- retourne un dictionnaire avec les lettres comme clés et leur fréquence comme valeurs

```python
frequence_lettres("Bonjour Python !")
# Retourne : {'b':1, 'o':3, 'n':2, 'j':1, 'u':1, 'r':1, 'p':1, 'y':1, 't':1, 'h':1}
```